"use strict";
exports.__esModule = true;
exports.CONTRACT_CYCLE = exports.CONTRACT_STATUS = exports.WITHDRAW_STATUS = exports.DEPOSIT_STATUS = void 0;
var DEPOSIT_STATUS;
(function (DEPOSIT_STATUS) {
    DEPOSIT_STATUS["PENDING"] = "Pending";
    DEPOSIT_STATUS["COMPLETED"] = "Completed";
    DEPOSIT_STATUS["CANCELED"] = "Canceled";
})(DEPOSIT_STATUS || (DEPOSIT_STATUS = {}));
exports.DEPOSIT_STATUS = DEPOSIT_STATUS;
var WITHDRAW_STATUS;
(function (WITHDRAW_STATUS) {
    WITHDRAW_STATUS["CONFIRMED"] = "Confirmed";
    WITHDRAW_STATUS["PENDING"] = "Pending";
    WITHDRAW_STATUS["COMPLETED"] = "Completed";
    WITHDRAW_STATUS["CANCELED"] = "Canceled";
})(WITHDRAW_STATUS || (WITHDRAW_STATUS = {}));
exports.WITHDRAW_STATUS = WITHDRAW_STATUS;
var CONTRACT_STATUS;
(function (CONTRACT_STATUS) {
    CONTRACT_STATUS["CONFIRMED"] = "Confirmed";
    CONTRACT_STATUS["PENDING"] = "Pending";
    CONTRACT_STATUS["COMPLETED"] = "Completed";
    CONTRACT_STATUS["CANCELED"] = "Canceled";
})(CONTRACT_STATUS || (CONTRACT_STATUS = {}));
exports.CONTRACT_STATUS = CONTRACT_STATUS;
var CONTRACT_CYCLE;
(function (CONTRACT_CYCLE) {
    CONTRACT_CYCLE[CONTRACT_CYCLE["1_MONTH"] = 30] = "1_MONTH";
    CONTRACT_CYCLE[CONTRACT_CYCLE["3_MONTH"] = 90] = "3_MONTH";
    CONTRACT_CYCLE[CONTRACT_CYCLE["6_MONTH"] = 180] = "6_MONTH";
    CONTRACT_CYCLE[CONTRACT_CYCLE["12_MONTH"] = 360] = "12_MONTH";
    CONTRACT_CYCLE[CONTRACT_CYCLE["18_MONTH"] = 540] = "18_MONTH";
})(CONTRACT_CYCLE || (CONTRACT_CYCLE = {}));
exports.CONTRACT_CYCLE = CONTRACT_CYCLE;
